### ISSUE TITLE
Floodline breaks lines right after?

### ISSUE THREAD

**Issue by fadijalal07** [GalaxyGamesMC/libscoreboard#3]
i had my code as ```$this->scoreboard->create($sender, "normal", "     §l§4Central§cPE §r§7OP Factions     ")
    ->setLine($sender, 0, "" . $rank . "§r" . " §f" . $sender->getName() . "")
    ->setLine($sender, 1, " §l§4Stats:")
    ->update($sender);```

and the line 1 didnt show up, it was blank e.g: 
![image](https://github.com/GalaxyGamesMC/libscoreboard/assets/65230268/a2e27b58-27f6-48cb-aac6-ca803d5cf922)
 and when i tried the same with like ```$this->scoreboard->create($sender, "normal", "     §l§4Central§cPE §r§7OP Factions     ")
    ->setLine($sender, 0, "" . $rank . "§r" . " §f" . $sender->getName() . "")
    ->floodLine($sender, 1, 2)
    ->setLine($sender, 3, " §l§4Stats:")
    ->update($sender);```

which gave me this 
![image](https://github.com/GalaxyGamesMC/libscoreboard/assets/65230268/70dffe51-277d-4685-800b-a9a025d2b42f)

**Comment by NTT1906** [comment]
I'm sorry for late replying.

**Comment by NTT1906** [comment]
I think my latest changes broke it

**Comment by NTT1906** [comment]
![image](https://github.com/GalaxyGamesMC/libscoreboard/assets/54394881/ec13e1eb-fddc-4e3c-a7bb-49fa13cec5d1)
![image](https://github.com/GalaxyGamesMC/libscoreboard/assets/54394881/44cf7c87-9e45-4ab9-befe-2ec4a726988e)
Fixed by [commit](https://github.com/GalaxyGamesMC/libscoreboard/commit/a0d2f88222caae17537bf63e6d06ef7a78915d11), in  [1.0.7](https://github.com/GalaxyGamesMC/libscoreboard/releases/tag/1.0.7)
